### ISSUE TITLE
Don't run

### ISSUE THREAD

**Issue by coc4tm** [CreeperMario/pytoolkit#1]
I am on Linux Mint 18 with Python 3 
Here is what i got : 
python log.py

  File "log.py", line 60
    self.backlog.configure(state="normal")
    ^

**Comment by CreeperMario** [comment]
I don't think that's the full error log, because it doesn't tell me anything useful.
Try running it in a new terminal session, and copy-paste the full Terminal window to a post.

**Comment by coc4tm** [comment]
cow@cow-pc ~/Bureau/trucs/pytoolkit-master/PyLogU $ python3 log.py
  File "log.py", line 60
    self.backlog.configure(state="normal")
    ^
IndentationError: unexpected indent

**Comment by CreeperMario** [comment]
Try the latest commit, I see what went wrong.

**Comment by coc4tm** [comment]
Hereis why i ot now (after installing tk) : 
```
cow@cow-pc ~/Bureau/trucs/pytoolkit-master/nv/pytoolkit-master/PyLogU $ python3 log.py
Traceback (most recent call last):
  File "log.py", line 22, in <module>
    import filedialog as tkfd
ImportError: No module named 'filedialog'
```

**Comment by coc4tm** [comment]
Well , this works with python2

**Comment by CreeperMario** [comment]
Which is interesting because it works on Python 3.3 running on Windows 7. When I get time, I'll try again and see if I can fix it.

Until then, I can almost guarantee it works on Python 2.7, because that's what I get on my development computer.

**Comment by coc4tm** [comment]
Great , this works now :)
